# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        LOG_LEVEL: "error, info"
        SQL_HOST: "127.0.0.1"
        SQL_HOST_READ: "127.0.0.1"
        SQL_HOST_WRITE: "127.0.0.1"
        SQL_PORT: "3306"
        SQL_DB: "db"
        SQL_USER: "root"
        SQL_PASS: "pass"
        SQL_DIALECT: "mysql"
        SQL_POOL_LIMIT: 100
        SQL_LOG: "false"
    - run: ssh-keygen -t rsa -b 2048 -q -N "12345" -m PEM -f private.key
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
