# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_LOG_LEVEL: "error, info"
        envkey_SQL_HOST: "127.0.0.1"
        envkey_SQL_HOST_READ: "127.0.0.1"
        envkey_SQL_HOST_WRITE: "127.0.0.1"
        envkey_SQL_PORT: "3306"
        envkey_SQL_DB: "db"
        envkey_SQL_USER: "root"
        envkey_SQL_PASS: "pass"
        envkey_SQL_DIALECT: mysql
        envkey_SQL_POOL_LIMIT: 100
        envkey_SQL_LOG: "false"
        file_name: .env
    - run: ssh-keygen -t rsa -b 2048 -q -N "12345" -m PEM -f private.key
    - run: cat .env
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test:cover
#     - name: Archive production artifacts
#       uses: actions/upload-artifact@v1
#       with:
#           name: dist
#           path: ./
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
          name: code-coverage-report
          path: coverage/lcov-report/index.html
